#version 440
layout(location = 0) in vec2 qt_TexCoord0;
layout(location = 0) out vec4 fragColor;
layout(std140, binding = 0) uniform buf {
    mat4 qt_Matrix;
    float qt_Opacity;
    float s0;
    float s1;
    float s2;
    float s3;
    float s4;
    float s5;
    float s6;
    float s7;
    float s8;
    float s9;
    float s10;
    float s11;
    float s12;
    float s13;
    float s14;
    float s15;
    float s16;
    float s17;
    float s18;
    float s19;
    float s20;
    float s21;
    float s22;
    float s23;
    float s24;
    float s25;
    float s26;
    float s27;
    float s28;
    float s29;
    float s30;
    float s31;
    float s32;
    float s33;
    float s34;
    float s35;
    float s36;
    float s37;
    float s38;
    float s39;
    float s40;
    float s41;
    float s42;
    float s43;
    float screenWidth;
    float screenHeight;
    float binCount;
} ubuf;
float sampleSpectrum(int index) {
    if (index == 0) return ubuf.s0;
    if (index == 1) return ubuf.s1;
    if (index == 2) return ubuf.s2;
    if (index == 3) return ubuf.s3;
    if (index == 4) return ubuf.s4;
    if (index == 5) return ubuf.s5;
    if (index == 6) return ubuf.s6;
    if (index == 7) return ubuf.s7;
    if (index == 8) return ubuf.s8;
    if (index == 9) return ubuf.s9;
    if (index == 10) return ubuf.s10;
    if (index == 11) return ubuf.s11;
    if (index == 12) return ubuf.s12;
    if (index == 13) return ubuf.s13;
    if (index == 14) return ubuf.s14;
    if (index == 15) return ubuf.s15;
    if (index == 16) return ubuf.s16;
    if (index == 17) return ubuf.s17;
    if (index == 18) return ubuf.s18;
    if (index == 19) return ubuf.s19;
    if (index == 20) return ubuf.s20;
    if (index == 21) return ubuf.s21;
    if (index == 22) return ubuf.s22;
    if (index == 23) return ubuf.s23;
    if (index == 24) return ubuf.s24;
    if (index == 25) return ubuf.s25;
    if (index == 26) return ubuf.s26;
    if (index == 27) return ubuf.s27;
    if (index == 28) return ubuf.s28;
    if (index == 29) return ubuf.s29;
    if (index == 30) return ubuf.s30;
    if (index == 31) return ubuf.s31;
    if (index == 32) return ubuf.s32;
    if (index == 33) return ubuf.s33;
    if (index == 34) return ubuf.s34;
    if (index == 35) return ubuf.s35;
    if (index == 36) return ubuf.s36;
    if (index == 37) return ubuf.s37;
    if (index == 38) return ubuf.s38;
    if (index == 39) return ubuf.s39;
    if (index == 40) return ubuf.s40;
    if (index == 41) return ubuf.s41;
    if (index == 42) return ubuf.s42;
    if (index == 43) return ubuf.s43;
    return 0.0;
}
vec3 hsv2rgb(vec3 c) {
    vec3 rgb = clamp(abs(mod(c.x * 6.0 + vec3(0.0, 4.0, 2.0), 6.0) - 3.0) - 1.0, 0.0, 1.0);
    return c.z * mix(vec3(1.0), rgb, c.y);
}
void main() {
    vec2 uv = qt_TexCoord0;
    float pixelX = floor(uv.x * ubuf.screenWidth);
    float barPixel = 1.0 - step(1.0, mod(pixelX, 2.0));
    float mirroredX = uv.x < 0.5 ? uv.x * 2.0 : (1.0 - uv.x) * 2.0;
    int bin = min(43, int(floor(mirroredX * ubuf.binCount)));
    float strength = clamp(sampleSpectrum(bin), 0.0, 1.0);
    float barTop = 1.0 - strength * 0.5;
    float body = step(barTop, uv.y) * barPixel;
    float cap = (1.0 - smoothstep(barTop - 0.002, barTop + 0.002, uv.y)) * barPixel;
    vec3 color = hsv2rgb(vec3(uv.x, 0.88, 1.0));
    float alpha = clamp(body * 0.72 + cap * 0.98, 0.0, 1.0);
    fragColor = vec4(color * alpha, alpha) * ubuf.qt_Opacity;
}
